name: Scheduled Trigger Demo
on:
  schedule:
    # Runs every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Manual trigger for testing

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Scheduled task
        run: |
          echo "Scheduled workflow executed at: $(date)"
          echo "Event: ${{ github.event_name }}"
